orbisgis/orbiswps

scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportCSVFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportDBFFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportGeoJsonFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportKMLFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportShapeFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Export/exportTSVFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Buffer/fixedDistanceBuffer.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Buffer/variableDistanceBuffer.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Convert/extractCenter.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Create/createGridOfPoints.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Create/createGridOfPolygons.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Create/fixedExtrudePolygons.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Create/variableExtrudePolygons.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Properties/geometryProperties.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Geometry2D/Transform/reprojectGeometries.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/csvToPointsTable.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importCSVFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importDBFFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importGPXFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importGeoJsonFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importOSMFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importShapeFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Import/importTSVFile.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Network/createGraph.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Table/deleteColumns.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Table/deleteRows.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Table/describeColumns.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Table/insertValues.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Table/joinTables.groovy

Fixes the processes.

---

client/src/main/java/org/orbiswps/client/api/WpsClient.java
scripts/pom.xml
scripts/src/main/java/org/orbiswps/scripts/WpsScriptPlugin.java
scripts/src/main/java/org/orbiswps/scripts/WpsScriptsPackage.java
scripts/src/test/java/org/orbiswps/scripts/WpsScriptPluginTest.java
server/src/main/java/org/orbiswps/server/WpsServer.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/controller/parser/ParserController.java
server/src/main/java/org/orbiswps/server/controller/process/ProcessIdentifier.java
server/src/main/java/org/orbiswps/server/controller/process/ProcessManager.java
server/src/main/java/org/orbiswps/server/utils/WpsScriptUtils.java
server/src/test/java/org/orbiswps/server/TestWpsServerGetProcesses.java
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java

Fixes the addProcess function.
Put the copy script functions as an utillity.
(issue orbisgis/orbisgis#1221)

Api Fixes.

---

scripts/pom.xml
scripts/src/main/java/org/orbiswps/scripts/WpsScriptPlugin.java
scripts/src/main/java/org/orbiswps/scripts/WpsScriptsPackage.java
server/src/main/java/org/orbiswps/server/utils/WpsScriptUtils.java

Now adds all the script contained in the resource folder instead of loading them one by one. (issue #13)

Some cleaning

---

server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/controller/process/ProcessIdentifier.java
server/src/main/java/org/orbiswps/server/controller/process/ProcessManager.java
server/src/main/java/org/orbiswps/server/controller/utils/Job.java
server/src/main/java/org/orbiswps/server/controller/utils/ObjectAnnotationConverter.java
server/src/main/java/org/orbiswps/server/execution/ProcessExecutionListener.java
server/src/main/java/org/orbiswps/server/execution/ProcessWorker.java
server/src/main/java/org/orbiswps/server/utils/ProcessTranslator.java
server/src/main/java/org/orbiswps/server/utils/ProgressMonitor.java
server/src/main/java/org/orbiswps/server/utils/WpsScriptUtils.java
server/src/main/java/org/orbiswps/server/utils/WpsServerProperties.java
server/src/main/resources/org/orbiswps/server/utils/basicWpsServer.properties
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java

Documentation.
Linked to the issue  #13.

Some documentation.

---

server/src/main/java/org/orbiswps/server/controller/parser/Parser.java
server/src/main/java/org/orbiswps/server/model/DataType.java
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java

Improve the DataType. Adds methods to convert int and string representation of the type get throw the SFS and JDBC utilities.

Improve the DataType class

---

scripts/src/main/java/org/orbiswps/scripts/WpsScriptsPackage.java
server/src/main/java/org/orbiswps/server/controller/parser/Parser.java
server/src/main/java/org/orbiswps/server/controller/parser/ProcessParser.java
server/src/main/java/org/orbiswps/server/controller/process/ProcessIdentifier.java
server/src/main/java/org/orbiswps/server/controller/utils/Job.java
server/src/main/java/org/orbiswps/server/model/DataType.java
server/src/main/java/org/orbiswps/server/model/ObjectFactory.java

Adds documentation.
Finish OrbisWPS part of the issue #13.

Documentation

---

scripts/src/main/java/org/orbiswps/scripts/WpsScriptPlugin.java
scripts/src/main/java/org/orbiswps/scripts/WpsScriptsPackage.java
scripts/src/test/java/org/orbiswps/scripts/WpsScriptPluginTest.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java

Clean the script module (warning, static strings ...) and adds tests. (linked to the issue #12)

Script bundle tests.

---

groovy-api/pom.xml
scripts/pom.xml
server/pom.xml

Updates the poms.

---

server/src/main/java/org/orbiswps/server/WpsServerImpl.java

Fixes the constructor the WpsServerImpl.

Fixes the constructor the WpsServerImpl.

---

pom.xml
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/execution/ProcessWorker.java
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java
server/src/test/java/org/orbiswps/server/model/WpsModelTest.java
server/src/test/resources/org/orbiswps/server/EnumerationLongProcess.groovy
server/src/test/resources/org/orbiswps/server/ascriptfolder/script1.groovy
server/src/test/resources/org/orbiswps/server/ascriptfolder/script2.groovy
server/src/test/resources/org/orbiswps/server/ascriptfolder/script3.groovy

Improve the way the WpsServerImpl manage the execution of a process when the previous ends.
Complete the WpsServerImpl test class.

WpsServerImpl tests

---

server/src/main/java/org/orbiswps/server/controller/parser/JDBCColumnParser.java
server/src/test/java/org/orbiswps/server/controller/parser/JDBCColumnParserTest.java

Add test class for the JDBCColumnParser. Liked to the issue #12.

Add test class for the JDBCColumnParser.

---

server/src/main/java/org/orbiswps/server/controller/parser/JDBCTableParser.java
server/src/test/java/org/orbiswps/server/controller/parser/JDBCTableParserTest.java

Add test class for the JDBCTableParser. Liked to the issue #12.

Add test class for the JDBCTableParser

---

server/src/main/java/org/orbiswps/server/controller/parser/JDBCValueParser.java
server/src/test/java/org/orbiswps/server/controller/parser/JDBCValueParserTest.java

Add test class for the JDBCValueParser. Liked to the issue #12.

Add test class for the JDBCValueParser

---

server/src/test/java/org/orbiswps/server/controller/parser/PasswordParserTest.java

Adds test class for the PasswordParser. Linked to the issue #12

Adds test class for the PasswordParser.

---

server/src/main/java/org/orbiswps/server/controller/parser/RawDataParser.java
server/src/test/java/org/orbiswps/server/controller/parser/ProcessParserTest.java
server/src/test/java/org/orbiswps/server/controller/parser/RawDataParserTest.java

Adds test class for the RawDataParser. Linked to the issue #12

Adds test class for the RawDataParser.

---

server/src/main/java/org/orbiswps/server/controller/parser/ParserController.java
server/src/test/java/org/orbiswps/server/controller/parser/TestParserController.java
server/src/test/resources/org/orbiswps/server/controller/parser/NoProcessingProcess.groovy
server/src/test/resources/org/orbiswps/server/controller/parser/SimpleProcess.groovy

Adds test class for the ParserController. Linked to the issue #12.

Adds test class for the ParserController.

---

scripts/src/test/java/org/orbiswps/scripts/WpsScriptPluginTest.java
server/src/main/java/org/orbiswps/server/WPS_2_0_Operations.java
server/src/main/java/org/orbiswps/server/WPS_2_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/WpsServer.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/utils/WpsServerProperties_2_0.java
server/src/main/java/org/orbiswps/server/utils/WpsServerUtils.java
server/src/test/java/org/orbiswps/server/TestWPS_2_0_OperationsImpl.java
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java

Moves all the methods from the WPS 2.0 standard to the dedicated class `WPS_2_0_OperationsImpl`.
Quite a big PR but it is only copy paste of piece of code and tests. Linked to the issue #36.

Moves all the methods from the WPS 2.0 standard to a dedicated class.

---

server/pom.xml
server/src/main/java/org/orbiswps/server/WPS_1_0_0_Operations.java
server/src/main/java/org/orbiswps/server/WPS_1_0_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/WPS_2_0_Operations.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/model/JaxbContainer.java
server/src/main/java/org/orbiswps/server/utils/WpsServerProperties_1_0_0.java

Implements the GetCapabilities of the 1.0.0 WPS. 
For that, a class named` WpsServerProperties_1_0_0` which is quite the same as the `WpsServerProperties_2_0` but with objects compatible with the WPS 1.0.0 version.
The class `WPS_1_0_0_Operations` contains all the WPS 1.0.0 operations.

Implements the getcapabilities of the 1.0.0 WPS.

---

server/src/main/java/org/orbiswps/server/WPS_1_0_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/WPS_2_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/utils/WpsServerProperties_1_0_0.java
server/src/main/resources/org/orbiswps/server/utils/basicWpsServer.properties

Adds the operation DescribeProcess 1.0.0 operation and methods to convert OWS 2 objects into OWS 1 version.

Adds DescribeProcess 1.0.0 operation.

---

server/src/main/java/org/orbiswps/server/WPS_1_0_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/test/java/org/orbiswps/server/TestWPS_1_0_0_OperationsImpl.java

Adds test class for the WPS 1.0.0 operations. Linked to the issue #36, #37, #38

Adds test class for the WPS 1.0.0 operations.

---

server/src/main/java/org/orbiswps/server/WPS_1_0_0_OperationsImpl.java
server/src/main/java/org/orbiswps/server/controller/parser/JDBCTableParser.java
server/src/main/java/org/orbiswps/server/controller/utils/FormatFactory.java
server/src/test/java/org/orbiswps/server/TestWPS_1_0_0_OperationsImpl.java

Fixes the describe process to make the orbisgis custom complexData compatible with other clients. Linked to the issue #36.

Compatibility with clients

---

server/src/main/java/org/orbiswps/server/WPS_2_0_OperationsImpl.java
server/src/test/java/org/orbiswps/server/TestWpsServerImpl.java

Fixes wps 2.0.0 GetResult operation.

Fixes wps 2.0.0 GetResult operation.

---

server/src/main/java/org/orbiswps/server/WpsServerImpl.java
server/src/main/java/org/orbiswps/server/utils/WpsServerProperties_2_0.java

Adds a constructor to the WpsServerImpl to give it the file configuration.

WpsServer cutomisation

---

scripts/pom.xml
scripts/src/main/java/org/orbiswps/scripts/WPSScriptExecute.java
scripts/src/test/java/org/orbiswps/scripts/WPSScriptTests.java
scripts/src/test/resources/org/orbiswps/scripts/basicWPSScript.groovy
scripts/src/test/resources/org/orbiswps/scripts/wpsScriptWithoutInput.groovy

A method plus some basic tests to demonstrate how to test a WPS groovy script without the server.

Wps script tests

---

README.md

Updates the readme.md file.

---

pom.xml
scripts/pom.xml

Updates the H2GIS version.

---

scripts/src/main/java/org/orbiswps/scripts/WpsScriptPlugin.java
scripts/src/main/resources/org/orbiswps/scripts/scripts/Select/attributeFiltering.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Select/expressionFiltering.groovy
scripts/src/main/resources/org/orbiswps/scripts/scripts/Select/spatialFiltering.groovy
scripts/src/test/java/org/orbiswps/scripts/WPSScriptTests.java

Add WPS scripts to select data on spatial, attribute or expression filtering

Wps select scripts

---

server/src/main/java/org/orbiswps/server/model/Enumeration.java

Fix bug on translation of enumeration.

Fix bug on translation of enumeration.

---

scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportCSVFile.groovy
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportDBFFile.groovy
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportGeoJsonFile.groovy
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportKMLFile.groovy
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportShapeFile.groovy
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Export/exportTSVFile.groovy
scripts/src/test/java/org/orbisgis/orbiswps/scripts/ExportScriptTests.java
scripts/src/test/java/org/orbisgis/orbiswps/scripts/ScriptTests.java
scripts/src/test/java/org/orbisgis/orbiswps/scripts/WPSScriptExecute.java

Change the method use to execute the script in order to test the processes. Now the output data are return by the method to be checked in the test.
Adds a test class for the export scripts.

Rework test part1

---

gettext-maven-plugin/pom.xml
gettext-maven-plugin/src/main/java/org/xnap/commons/maven/gettext/AbstractGettextMojo.java
gettext-maven-plugin/src/main/java/org/xnap/commons/maven/gettext/DistMojo.java
gettext-maven-plugin/src/main/java/org/xnap/commons/maven/gettext/GettextWpsMojo.java
gettext-maven-plugin/src/main/java/org/xnap/commons/maven/gettext/LoggerStreamConsumer.java
pom.xml
scripts/pom.xml
scripts/src/main/java/org/orbisgis/orbiswps/scripts/WpsScriptPlugin.java
scripts/src/main/resources/org/orbisgis/orbiswps/scripts/translation/keys.pot
scripts/src/test/java/org/orbisgis/orbiswps/scripts/WpsScriptPluginTest.java
service-api/pom.xml
service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/WpsScriptBundle.java
service/pom.xml
service/src/main/java/org/orbisgis/orbiswps/service/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/WPS_2_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/controller/process/ProcessIdentifier.java
service/src/main/java/org/orbisgis/orbiswps/service/utils/ProcessTranslator.java

Updates the wps bundle to be able to manage the translation with I18n library.
Adds a modified version of the gettext-maven-plugin which is able to parse the WPS groovy annotations.

I18n in script bundles.

---

service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/process/ProcessManager.java

Fixes the process removing. 

---

README.md
service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/process/ProcessIdentifier.java
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/process/ProcessIdentifierImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/process/ProcessManager.java
service/src/main/java/org/orbisgis/orbiswps/service/process/ProcessWorker.java
service/src/test/java/org/orbisgis/orbiswps/service/TestWpsServerImpl.java

Fixes the scripts properties.

---

scripts/src/main/java/org/orbisgis/orbiswps/scripts/WpsScriptPlugin.java

Fix for windows. Issue orbisgis/orbisgis#1295

Fix for windows. 

---

pom.xml
scripts/pom.xml

Fixes the h2gis version to the last stable.

Fixes the h2gis version to the last stable.

---

gettext-maven-plugin/pom.xml
pom.xml
scripts/pom.xml
testsuite/pom.xml
testsuite/src/test/java/org/orbisgis/orbiswps/testsuite/AbstractTestSuite.java

Change the H2GIS version and adds a test module for WPS.

Change the H2GIS version and adds a test module for WPS.

---

service/src/main/java/org/orbisgis/orbiswps/service/model/DataType.java

Fixes the datatype number/numeric.

Fixes the datatype number/numeric.

---

scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Geometry2D/Topology/sharedPart.groovy
scripts/src/test/java/org/orbisgis/orbiswps/scripts/ScriptTests.java

WPS to extract the shared part of a geometry with each other
about #82

WPS Shared part

---

scripts/src/main/java/org/orbisgis/orbiswps/scripts/WpsScriptPlugin.java
service/src/main/java/org/orbisgis/orbiswps/service/model/DataType.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_2_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/utils/ObjectAnnotationConverter.java
service/src/test/java/org/orbisgis/orbiswps/service/TestWpsServerImpl.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_OperationsImpl.java
service/src/test/java/org/orbisgis/orbiswps/service/parser/ProcessParserTest.java
testsuite/src/test/java/org/orbisgis/orbiswps/testsuite/DescribeProcessTest.java
testsuite/src/test/java/org/orbisgis/orbiswps/testsuite/GetCapabilitiesTest.java
testsuite/src/test/java/org/orbisgis/orbiswps/testsuite/WpsServiceFactory.java

Adds the DescribeProcess tests.

Adds the DescribeProcess tests. 

---

service/pom.xml
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WpsServerProperties_1_0_0.java
testsuite/src/test/java/org/orbisgis/orbiswps/testsuite/WpsServiceFactory.java

Start making wpsservice use a json file for configuration instead of a properties file.

Json config file

---

service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WpsServerProperties_1_0_0.java
service/src/main/resources/org/orbisgis/orbiswps/service/operations/wps_1_0_0_conf.json
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_OperationsImpl.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWpsServiceProperty_1_0_0.java
service/src/test/resources/org/orbisgis/orbiswps/service/operations/fullWpsService100.json
service/src/test/resources/org/orbisgis/orbiswps/service/operations/minWpsService100.json

Adds test class for the WPS 1.0.0 property class.

Adds test class for the WPS 1.0.0 property class.

---

service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/operations/WPS_1_0_0_Operations.java
service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/operations/WPS_2_0_Operations.java
service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/operations/WpsOperations.java
service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/operations/WpsProperties.java
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_2_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WpsServerProperties_1_0_0.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WpsServerProperties_2_0.java
service/src/test/java/org/orbisgis/orbiswps/service/TestWpsServerGetProcesses.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_GetCapabilities.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWpsServiceProperty_1_0_0.java
service/src/test/resources/org/orbisgis/orbiswps/service/operations/fullWpsService100.json
service/src/test/resources/org/orbisgis/orbiswps/service/operations/minWpsService100.json

Makes the WPS properties classes osgi component. Cover wps 1.0.0 property class with test.

WPS properties classes as osgi component

---

service-api/src/main/java/org/orbisgis/orbiswps/serviceapi/operations/WPS_1_0_0_Operations.java
service/pom.xml
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_DescribeProcess.java

Finishes the test of DescribeProcess operation. 
Remove useless JTS dependency.

End of DescribeProcess test and dependency fix

---

service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WpsServerProperties_1_0_0.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_Execute.java

Adds test for passing inputs and output as references. 
Adds test for the execution.

Adds execute tests

---

service/pom.xml
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_JobRunner.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_Execute.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_2_0_OperationsImpl.java
service/src/test/resources/org/orbisgis/orbiswps/service/operations/jdbcTableScript.groovy
service/src/test/resources/org/orbisgis/orbiswps/service/operations/longRunScript.groovy

Adds test for :
- The 'lineage' parameter
- Request of a rawData output
- Using the geojson format for the JDBCTable in/output

Adds last Execute tests

---

scripts/src/main/resources/org/orbisgis/orbiswps/scripts/scripts/Table/describeColumns.groovy
service/src/main/java/org/orbisgis/orbiswps/service/WpsServerImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_JobRunner.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/parser/JDBCTableParser.java
service/src/main/java/org/orbisgis/orbiswps/service/utils/ObjectAnnotationConverter.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_DescribeProcess.java
service/src/test/java/org/orbisgis/orbiswps/service/operations/TestWPS_1_0_0_Execute.java
service/src/test/resources/org/orbisgis/orbiswps/service/operations/fullWpsService100.json

Removes the text/xml and gml formats.
Fixes the behaviour of the reference of JDBCTable.
Other minor fixes.

Fix reference and formats.

---

pom.xml
scripts/src/test/java/org/orbisgis/orbiswps/scripts/ScriptTests.java
service/pom.xml
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_JobRunner.java
service/src/main/java/org/orbisgis/orbiswps/service/operations/WPS_1_0_0_OperationsImpl.java
service/src/main/java/org/orbisgis/orbiswps/service/utils/WpsDataUtils.java
service/src/test/java/org/orbisgis/orbiswps/service/utils/DataProcessingTest.java
service/src/test/resources/org/orbisgis/orbiswps/service/operations/fullScript.groovy

Updates the JTS and H2GIS dependencies to use custom builds

TempoUpdates the JTS and H2GIS dependencies.
